spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vas2
    username: root
    password: root
#    initialization-mode: ALWAYS
    
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: false
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect